'use server';

import { revalidatePath } from 'next/cache';

import { requireOperatorRole, requireViewer } from '@/lib/auth/session';
import { fail, parseForm, succeed, type FormState } from '@/lib/forms';
import { createClient } from '@/lib/supabase/server';
import { formatCents } from '@/lib/money';
import { describeVoucher } from '@/lib/promotions/vouchers';
import {
  voucherCodeSchema,
  voucherSchema,
  voucherToggleSchema,
} from '@/lib/validation/promotions';
import type { VoucherKind } from '@/lib/supabase/database.types';

/**
 * Writes for promotions.
 *
 * Thin, like the other action modules: validate, authenticate, call the
 * Postgres function. The code itself is generated by `create_voucher()` and
 * the expiry is computed there — neither is a number a browser gets to send.
 */

export async function createVoucher(_prev: FormState, formData: FormData): Promise<FormState> {
  const parsed = parseForm(voucherSchema, formData);
  if (!parsed.ok) return parsed.state;

  await requireOperatorRole(parsed.data.operator_id);

  const supabase = await createClient();
  const { data: code, error } = await supabase.rpc('create_voucher', {
    p_operator_id: parsed.data.operator_id,
    p_kind: parsed.data.kind,
    p_value: parsed.data.value,
    p_window: parsed.data.validity,
    p_max_uses: parsed.data.max_uses,
  });

  if (error || !code) {
    // The function raises messages written for the operator.
    return fail(error?.message ?? 'We could not create that code. Try again in a moment.');
  }

  revalidatePath(`/operator/${parsed.data.operator_id}/promotions`);
  return succeed(
    `${code} is live — ${describeVoucher(parsed.data.kind, parsed.data.value, formatCents)}. ` +
      'Give it to passengers however you reach them.',
  );
}

/**
 * Withdrawing a code, and putting it back. Never a delete: bookings that
 * already spent it point at the row, and what an operator once offered is part
 * of their own record.
 */
export async function setVoucherActive(formData: FormData): Promise<void> {
  const parsed = parseForm(voucherToggleSchema, formData);
  if (!parsed.ok) return;

  await requireOperatorRole(parsed.data.operator_id);

  const supabase = await createClient();
  await supabase.rpc('set_voucher_active', {
    p_voucher_id: parsed.data.voucher_id,
    p_active: parsed.data.active === 'on',
  });

  revalidatePath(`/operator/${parsed.data.operator_id}/promotions`);
}

export type VoucherCheck =
  | { ok: true; code: string; kind: VoucherKind; value: number }
  | { ok: false; message: string };

/**
 * What the booking page asks before the passenger commits.
 *
 * Display only — `request_booking()` resolves the code again, holding the row,
 * and it is that answer the passenger is charged. This exists so nobody has to
 * press "Request seat" to find out whether their code worked.
 */
export async function checkVoucher(
  departureId: string,
  code: string,
): Promise<VoucherCheck> {
  const parsed = voucherCodeSchema.safeParse({ departure_id: departureId, code });
  if (!parsed.success) {
    return { ok: false, message: 'A voucher code is six letters or numbers.' };
  }

  await requireViewer(`/departures/${departureId}`);

  const supabase = await createClient();
  const { data, error } = await supabase.rpc('check_voucher', {
    p_departure_id: parsed.data.departure_id,
    p_code: parsed.data.code,
  });

  if (error) {
    return { ok: false, message: error.message };
  }

  const voucher = data?.[0];
  if (!voucher) {
    return { ok: false, message: 'That code is not one this operator has issued.' };
  }

  return { ok: true, code: voucher.code, kind: voucher.kind, value: voucher.value };
}
